server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://47.102.131.233:3306/credit
    driverClassName: com.mysql.cj.jdbc.Driver
    username: student
    password: Pass.123
mybatis:
  mapper-locations:   classpath:/mapping/*.xml
  config-location:  classpath:/mybatis-config.xml
  type-aliases-package: com.p2p.lending.dao

logging:
  level:
    com:
      example:
        mapper : debug