server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://47.102.131.233:3306/credit
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ShiYuzhu.18
  mvc:
    view:
      prefix: /
      suffix: .jsp
    pathmatch:
      use-suffix-pattern: true
mybatis:
  mapper-locations:   classpath:/mapping/*.xml
  config-location:  classpath:/mybatis-config.xml
  type-aliases-package: com.p2p.lending.biaoMapperDao

logging:
  level:
    com:
      example:
        mapper : debug